coverage:
  status:
    patch:
      default:
        target: 100.0
ignore:
  - ^lib/timer/.*
  - (?s:.*/__init__\.py.*)\Z
  - ^lib/encoder/.*  # ignore folders and all its contents
  - ^lib/microphone/.*  # ignore folders and all its contents
